name: Automatic increase
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      packages: write
      attestations: write
      id-token: write
    steps:
    - uses: actions/checkout@v4
      with:
        ref: main
        fetch-depth: 0
    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}
    - run: |
        latest_tag=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
        MAJOR=$(echo "$latest_tag" | cut -d . -f 1)
        MAJOR=${MAJOR#v}  # Remove the 'v' prefix
        MINOR=$(echo "$latest_tag" | cut -d . -f 2)
        PATCH=$(echo "$latest_tag" | cut -d . -f 3 | cut -d - -f 1)
        timestamp=$(date -u +"%Y%m%d.%H%M")
        pre_version="v${MAJOR}.${MINOR}.${PATCH}-pre-${timestamp}"
        echo "pre_version=$pre_version" >> $GITHUB_ENV
        echo "version_major=$MAJOR" >> $GITHUB_ENV
        echo "version_minor=$MINOR" >> $GITHUB_ENV
        IMG="ghcr.io/${{github.repository}}"
        IMG=${IMG@L} # lower case the image
        echo "IMG=$IMG" >> $GITHUB_ENV
    - run: |
        git tag "${{ env.pre_version }}"
        git push origin "${{ env.pre_version }}"
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          ${{ env.IMG }}:${{ env.pre_version }}
          ${{ env.IMG }}:${{ env.version_major }}.${{ env.version_minor }}.latest
          ${{ env.IMG }}:${{ env.version_major }}.latest
          ${{ env.IMG }}:latest