name: Auto Patch Release

on:
  push:
    branches: [ main ]

jobs:
  bump-patch-version:
    runs-on: ubuntu-24.04

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Read and bump patch version
        id: bump
        run: |
          set -euo pipefail

          version=$(cat VERSION | sed 's/^v//')
          IFS='.' read -r major minor patch <<< "$version"
          new_patch=$((patch + 1))
          new_version="v$major.$minor.$new_patch"

          echo "New version: $new_version"
          echo "$new_version" > VERSION
          echo "version=$new_version" >> $GITHUB_OUTPUT

      - name: Commit and tag new version
        run: |
          git add VERSION
          git commit -m "ci: bump patch version to ${{ steps.bump.outputs.version }}"
          git tag ${{ steps.bump.outputs.version }}
          git push origin HEAD
          git push origin ${{ steps.bump.outputs.version }}
  