name: Release
on:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+"]
jobs:
  build:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      packages: write
      attestations: write
      id-token: write
    steps:
    - uses: actions/checkout@v4
    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}
    - name: Parse version info from tag
      run: |
        # GITHUB_REF is like refs/tags/v2.3.5, so strip the first 11 chars
        VERSION=${GITHUB_REF:11}
        MAJOR=$(echo "$VERSION" | cut -d . -f 1)
        MINOR=$(echo "$VERSION" | cut -d . -f 2)
        PATCH=$(echo "$VERSION" | cut -d . -f 3)
        PATCH=$((PATCH + 1))
        timestamp=$(date -u +"%Y%m%d.%H%M")
        pre_version="v${MAJOR}.${MINOR}.${PATCH}-pre-${timestamp}"
        echo "pre_version=$pre_version" >> $GITHUB_ENV
        echo "version=$VERSION" >> $GITHUB_ENV
        echo "version_major=$MAJOR" >> $GITHUB_ENV
        echo "version_minor=$MINOR" >> $GITHUB_ENV
        IMG="ghcr.io/${{github.repository}}"
        IMG=${IMG@L} # lower case the image
        echo "IMG=$IMG" >> $GITHUB_ENV
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          ${{ env.IMG }}:${{ env.version }}
          ${{ env.IMG }}:${{ env.version_major }}.${{ env.version_minor }}.latest
          ${{ env.IMG }}:${{ env.version_major }}.latest
          ${{ env.IMG }}:latest
    - uses: actions/checkout@v4
      with:
        ref: main
        fetch-depth: 0
        path: main-branch
    - working-directory: ./main-branch
      run: |
        git tag "${{ env.pre_version }}"
        git push origin "${{ env.pre_version }}"
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        platforms: linux/amd64,linux/arm64
        context: ./main-branch
        push: true
        tags: |
          ${{ env.IMG }}:${{ env.pre_version }}
          ${{ env.IMG }}:${{ env.version_major }}.${{ env.version_minor }}.latest
          ${{ env.IMG }}:${{ env.version_major }}.latest
          ${{ env.IMG }}:latest